<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nevonex" nsURI="www.bosch.com/nevonex" nsPrefix="nevonex">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="version" value="8.4.18"/>
  </eAnnotations>
  <eSubpackages name="common" nsURI="com.bosch.nevonex.common" nsPrefix="common">
    <eClassifiers xsi:type="ecore:EEnum" name="ProviderEnum">
      <eLiterals name="GPS_TCProvider" literal="GPS_TCProvider"/>
      <eLiterals name="ImplementProvider" value="1" literal="ImplementProvider"/>
      <eLiterals name="ISOPGNProvider" value="2" literal="ISOPGNProvider"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ConnectionTypeEnum">
      <eLiterals name="MQTT" literal="MQTT"/>
      <eLiterals name="CAN" value="1" literal="CAN"/>
      <eLiterals name="GPIO" value="2" literal="GPIO"/>
      <eLiterals name="GPS" value="3" literal="GPS"/>
      <eLiterals name="ISOBUS" value="4" literal="ISOBUS"/>
      <eLiterals name="Serial" value="5" literal="Serial"/>
      <eLiterals name="WIFI" value="6" literal="WIFI"/>
      <eLiterals name="SATELLITE" value="7" literal="SATELLITE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PlatformServicesEnum">
      <eLiterals name="CLOUD_DOWNLOAD" literal="Cloud_Download"/>
      <eLiterals name="CLOUD_UPLOAD" value="1" literal="Cloud_Upload"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HMIServicesEnum">
      <eLiterals name="CUSTOMUI" literal="com.bosch.nevonex.customui.impl.UIWebServiceProvider"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAbsolutePosition" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="AbsolutePosition"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITopicObject" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="TopicObject"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbsolutePosition" eSuperTypes="#//common/IAbsolutePosition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="altitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopicObject" eSuperTypes="#//common/ITopicObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICommonFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="exception" nsURI="com.bosch.nevonex.exception" nsPrefix="exception">
    <eClassifiers xsi:type="ecore:EClass" name="IExceptionFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="fcb" nsURI="com.bosch.nevonex.fcb" nsPrefix="fcb">
    <eClassifiers xsi:type="ecore:EEnum" name="SubscriberEnum">
      <eLiterals name="FIL" literal="FIL"/>
      <eLiterals name="FGF" value="1" literal="FGF"/>
      <eLiterals name="ALL" value="2" literal="ALL"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IFCALController" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="FCALController"/>
      </eAnnotations>
      <eOperations name="setMachineUpdate">
        <eParameters name="machine" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        <eParameters name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="payload" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="details" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="publish">
        <eParameters name="interfaceKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="interfaceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="payloadValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="subscriber" eType="#//fcb/SubscriberEnum"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FCALController">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="FCALController"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IConnectionFactory" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactory"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPublishConnectionFactory" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PublishConnectionFactory"/>
    <eClassifiers xsi:type="ecore:EClass" name="ISubscribeConnectionFactory" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubscribeConnectionFactory"/>
    <eClassifiers xsi:type="ecore:EClass" name="IFcbFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="fcal" nsURI="com.bosch.nevonex.fcal" nsPrefix="fcal">
    <eClassifiers xsi:type="ecore:EClass" name="IBulkProcessor" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="BulkProcessor"/>
      </eAnnotations>
      <eOperations name="executeBulkOperations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BulkProcessor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="BulkProcessor"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IFcalFactory" abstract="true" interface="true"/>
<eClassifiers xsi:type="ecore:EClass" name="GPS_INFO_R" eSuperTypes="#//types/IArrayType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This Structure provides GPS signal quality"/>
        <details key="arrayfeatures" value="latitude,longitude,altitude,positionTime,hDOP,pDOP,numberOfSattelites"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="altitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hDOP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.0f">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pDOP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.0f">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSattelites" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="access" value="Read"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="types" nsURI="com.bosch.nevonex.types" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="IArrayType" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPropertyChange" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ITypesFactory" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyChange" eSuperTypes="#//types/IPropertyChange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="listeners" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eOperations name="addPropertyChangeListener">
        <eParameters name="_listener" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removePropertyChangeListener">
        <eParameters name="_listener" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="notifyPropertyChange">
        <eParameters name="_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="_oldValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="_newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IMachine"/>
    <eClassifiers xsi:type="ecore:EClass" name="IMachineProvider">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//fcb/FCALController"/>
      <eOperations name="createMachines">
        <eParameters name="_stream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="constructChildTypes">
        <eParameters name="_parent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="_parentObj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="_path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="initMachineProvider"/>
      <eOperations name="getTopicElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eParameters name="_index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="stopMachineProvider"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="customui" nsURI="com.bosch.nevonex.customui" nsPrefix="customui">
    <eClassifiers xsi:type="ecore:EEnum" name="PortEnum">
      <eLiterals name="HTTP" value="8080" literal="HTTP"/>
      <eLiterals name="WS" value="8081" literal="WS"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAbstractWebsocketEndPoint" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractWebsocketEndPoint"/>
    <eClassifiers xsi:type="ecore:EClass" name="INevonexRoute" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="NevonexRoute"/>
    <eClassifiers xsi:type="ecore:EClass" name="IUIWebServiceProvider" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="UIWebServiceProvider"/>
    <eClassifiers xsi:type="ecore:EClass" name="ICustomuiFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="cloud" nsURI="com.bosch.nevonex.cloud" nsPrefix="cloud">
    <eClassifiers xsi:type="ecore:EClass" name="ICloudDownload" instanceClassName="com.bosch.fsp.runtime.feature.ICloudDownload"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cloud" eSuperTypes="#//cloud/ICloudDownload #//types/PropertyChange">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Cloud_Download" value="true"/>
      </eAnnotations>
      <eOperations name="processDownloadMessage">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="It processes the message/file received from cloud."/>
        </eAnnotations>
        <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="initPlatformService" eExceptions="#//exception/MachineInitException"/>
      <eOperations name="startPlatformService" eExceptions="#//exception/MachineInitException"/>
      <eOperations name="stopPlatformService" eExceptions="#//exception/NevonexException"/>
      <eOperations name="getFilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns file path of latest downloaded file. (ICloudDownload contract)"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="uploadData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given data to Nevonex Cloud"/>
        </eAnnotations>
        <eParameters name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Data to be uploaded"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="uploadData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given data to Nevonex Cloud using wifi or satellite based on the selected connection type."/>
        </eAnnotations>
        <eParameters name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Data to be uploaded"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="connectionType" eType="#//common/ConnectionTypeEnum">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Type of communication which should be used for uploading data. The allowable connection types are WIFI,SATELLITE. If this value is null WIFI is selected by default."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="uploadFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given file to Nevonex Cloud"/>
        </eAnnotations>
        <eParameters name="file" eType="#//types/File">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="File which has to be uploaded"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="uploadFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given file to Nevonex Cloud"/>
        </eAnnotations>
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Absolute Path of the file"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="uploadFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given file to Nevonex Cloud"/>
        </eAnnotations>
        <eParameters name="file" eType="#//types/File">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="File which has to be uploaded"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="connectionType" eType="#//common/ConnectionTypeEnum">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Type of communication which should be used for uploading File. The allowable connection types are WIFI,SATELLITE. If this value is null WIFI is selected by default."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="uploadFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Uploads given file to Nevonex Cloud"/>
        </eAnnotations>
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Absolute Path of the file"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Priority of the upload 1. High, 2. Medium, 3.Low"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="connectionType" eType="#//common/ConnectionTypeEnum">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Type of communication which should be used for uploading File. The allowable connection types are WIFI,SATELLITE. If this value is null WIFI is selected by default."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="device2device" nsURI="com.bosch.nevonex.device2device" nsPrefix="device2device">
    <eClassifiers xsi:type="ecore:EClass" name="IDeviceDownload" instanceClassName="com.bosch.fsp.runtime.feature.IDeviceDownload"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Device2Device" eSuperTypes="#//device2device/IDeviceDownload #//types/PropertyChange">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Device2Device_Download" value="true"/>
      </eAnnotations>
      <eOperations name="processDownloadMessage">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="It processes the message/file received from Connected Device."/>
        </eAnnotations>
        <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="initPlatformService" eExceptions="#//exception/MachineInitException"/>
      <eOperations name="startPlatformService" eExceptions="#//exception/MachineInitException"/>
      <eOperations name="stopPlatformService" eExceptions="#//exception/NevonexException"/>
      <eOperations name="sendCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Sends given command to the connected device"/>
        </eAnnotations>
        <eParameters name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Command which has to be sent to the connected device"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="isDeviceConnected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Checks whether device is connected to the Nevonex CCU. &#xA;Returns true if connected, false otherwise."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="sendFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Sends file present at the given path to the connected device."/>
        </eAnnotations>
        <eParameters name="file" eType="#//types/File">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="File which has to be sent"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="sendFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          eExceptions="#//exception/CloudBadRequestException #//exception/CloudUnAuthorizedException #//exception/CloudAccessDeniedException #//exception/CloudConnectionException #//exception/PlatformServiceException #//exception/FileNotFoundException #//exception/IOException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Sends the give file to connected device."/>
        </eAnnotations>
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Absolute path of the file."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="gps_tc" nsURI="com.bosch.nevonex.gps_tc" nsPrefix="gps_tc">
    <eClassifiers xsi:type="ecore:EClass" name="IGPS_TC" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="containedIn" value="GPS_TCProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="active_TC_GPS_source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/3954;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionofGpsSensor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/123;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tcGpsInfo" eType="#//fcal/GPS_INFO_R">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/3904;"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GPS_TC" eSuperTypes="#//common/TopicObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="interfaceDetails" value="fek/3954;fek/123;fek/3904;"/>
        <details key="interfaceDetailsType" value="3954/ENUM_TYPE/Active_TC_GPS_source;123/GPS_TYPE/PositionofGpsSensor;3904/ARRAY_TYPE/GPS_INFO_R;"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IGPS_TCProvider" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="gPS_TC" eType="#//gps_tc/IGPS_TC" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GPS_TCProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IGps_tcFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="implement" nsURI="com.bosch.nevonex.implement" nsPrefix="implement">
    <eClassifiers xsi:type="ecore:EClass" name="IImplement" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="containedIn" value="ImplementProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifetimeWorkingHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/350;"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Implement" eSuperTypes="#//common/TopicObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="interfaceDetails" value="fek/350;"/>
        <details key="interfaceDetailsType" value="350/DOUBLE_TYPE/LifetimeWorkingHours;"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IImplementProvider" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implement" eType="#//implement/IImplement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImplementProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IImplementFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="isopgn" nsURI="com.bosch.nevonex.isopgn" nsPrefix="isopgn">
    <eClassifiers xsi:type="ecore:EClass" name="IISOPGN" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="containedIn" value="ISOPGNProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accpedPos1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/215;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ambAirt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/306;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="brkPedPos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/9336;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="engFuRatePerTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/294;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="engSpd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/224;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="engTotOperHrs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/273;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuLvlPer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/314;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuLvlPer2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/9173;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gndBasdMacSpd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/267;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tachoVehSpd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/8744;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalVehDist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/8746;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totVehHrs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/276;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whlBasdMacSpd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/263;"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISOPGN" eSuperTypes="#//common/TopicObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="interfaceDetails" value="fek/215;fek/306;fek/9336;fek/294;fek/224;fek/273;fek/314;fek/9173;fek/267;fek/8744;fek/8746;fek/276;fek/263;"/>
        <details key="interfaceDetailsType" value="215/FLOAT_TYPE/AccpedPos1;306/FLOAT_TYPE/AmbAirt;9336/FLOAT_TYPE/BrkPedPos;294/FLOAT_TYPE/EngFuRatePerTime;224/FLOAT_TYPE/EngSpd;273/FLOAT_TYPE/EngTotOperHrs;314/FLOAT_TYPE/FuLvlPer;9173/FLOAT_TYPE/FuLvlPer2;267/FLOAT_TYPE/GndBasdMacSpd;8744/FLOAT_TYPE/TachoVehSpd;8746/LONG_TYPE/TotalVehDist;276/FLOAT_TYPE/TotVehHrs;263/FLOAT_TYPE/WhlBasdMacSpd;"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IISOPGNProvider" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iSOPGN" eType="#//isopgn/IISOPGN" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISOPGNProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IIsopgnFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="platform_service" nsURI="com.bosch.nevonex.platform_service" nsPrefix="platform_service">
    <eClassifiers xsi:type="ecore:EClass" name="IPlatform_Service" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="containedIn" value="Platform_ServiceProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="download" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="receive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="interfaceDetails" value="fek/0;"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Platform_Service" eSuperTypes="#//common/TopicObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="Machine"/>
        <details key="interfaceDetails" value="fek/0;fek/0;fek/0;fek/0;fek/0;fek/0;"/>
        <details key="interfaceDetailsType" value="0/UNKNOWN_TYPE/Download;0/UNKNOWN_TYPE/UploadData;0/UNKNOWN_TYPE/UploadFile;0/UNKNOWN_TYPE/Receive;0/UNKNOWN_TYPE/SendCommand;0/UNKNOWN_TYPE/SendFile;"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPlatform_ServiceProvider" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platform_Service" eType="#//platform_service/IPlatform_Service" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Platform_ServiceProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="role" value="MachineProvider"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPlatform_serviceFactory" abstract="true" interface="true"/>
  </eSubpackages>
  <eSubpackages name="main" nsURI="com.bosch.nevonex.main" nsPrefix="main">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="Provider" value="GPS_TC provider:gps_tc,Implement provider:implement,ISOPGN provider:isopgn,Platform_Service provider:platform_service"/>
      <details key="AppControllerName" value="MainController"/>
      <details key="Timer" value="1000"/>
      <details key="isCustomUI" value="true"/>
      <details key="hasUserControls" value="false"/>
      <details key="UDInputListeners" value=""/>
      <details key="PlatformServices" value="Download,Upload Data,Upload File,Receive,Send Command,Send File"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationMain">
      <eOperations name="addListenersForUserDefinedControls">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method adds property change listeners for user defined widgets which are created using feature designer to this generated feature application."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="initializeMachineProviders">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method initializes the machines which are required to run the feature with their corresponding dom providers."/>
        </eAnnotations>
        <eParameters name="provider" eType="#//main/MachineProvider"/>
      </eOperations>
      <eOperations name="addProcessTimer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method schedules the runnable controller class to be called in given particular interval of time."/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timerTriggered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MachineProvider" instanceClassName="com.bosch.fsp.runtime.feature.IMachineProvider"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyChangeListener" instanceClassName="java.beans.PropertyChangeListener"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Runnable" instanceClassName="java.lang.Runnable"
        abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationInputData">
      <eStructuralFeatures xsi:type="ecore:EReference" name="gPS_TC" eType="#//main/GPS_TC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implement" eType="#//main/Implement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iSOPGN" eType="#//main/ISOPGN"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platform_Service" eType="#//main/Platform_Service"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MainController" eSuperTypes="#//main/Runnable #//main/ApplicationInputData">
      <eOperations name="run"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureManagerListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="IgnitionStateListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="MachineConnectListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="IController"/>
    <eClassifiers xsi:type="ecore:EClass" name="CloudDownloadListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="Device2DeviceDownloadListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="SampleGetService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//main/MainController"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SamplePostService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//main/MainController"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SamplePutService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//main/MainController"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SampleDeleteService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#//main/MainController"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UIWebsocketEndPoint"/>
    <eClassifiers xsi:type="ecore:EClass" name="GPS_TC"/>
    <eClassifiers xsi:type="ecore:EClass" name="Implement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ISOPGN"/>
    <eClassifiers xsi:type="ecore:EClass" name="Platform_Service"/>
  </eSubpackages>
</ecore:EPackage>
